openapi: 3.0.0
paths:
  /auth/sign-in-one-c:
    post:
      operationId: AuthController_signInOneC
      summary: Авторизация при помощи 1C
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequestDto'
      responses:
        '200':
          description: ''
      tags:
        - auth
  /auth/sign-out:
    post:
      operationId: AuthController_signOut
      summary: Выход из сессии
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - auth
  /auth/session-info:
    get:
      operationId: AuthController_getSessionInfo
      summary: Получение информации о сессии
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionInfoDto'
      tags:
        - auth
  /panel/bad-applications:
    get:
      operationId: PanelController_getBadApplications
      summary: Получение информации о отказах, возвратах, и пропущенных звонках
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BadApplication'
      tags:
        - panel
  /panel/categories:
    get:
      operationId: PanelController_getCategories
      summary: Получение категорий
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
      tags:
        - panel
  /panel/applications-sales:
    get:
      operationId: PanelController_getApplicationSale
      summary: Получение заявок и продаж
      parameters:
        - name: title
          required: true
          in: query
          schema:
            type: string
        - name: type
          required: true
          in: query
          schema:
            type: string
        - name: page
          required: true
          in: query
          schema:
            type: string
        - name: count
          required: true
          in: query
          schema:
            type: string
        - name: text
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSaleDto'
      tags:
        - panel
  /panel/move-application-sale:
    post:
      operationId: PanelController_moveApplicationSale
      summary: Перемещение заявок и продаж
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoveApplicationSaleDto'
      responses:
        '200':
          description: ''
      tags:
        - panel
  /panel/create-sale:
    post:
      operationId: PanelController_createSale
      summary: Создание продажи
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSaleDto'
      responses:
        '200':
          description: ''
      tags:
        - panel
  /panel/organizations-bills:
    get:
      operationId: PanelController_getOrgsBills
      summary: Получение организация и счетов
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrgsBills'
      tags:
        - panel
  /panel/cancels:
    get:
      operationId: PanelController_getCancels
      summary: Отказы
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: string
        - name: count
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSaleDto'
      tags:
        - panel
  /panel/returns:
    get:
      operationId: PanelController_getReturns
      summary: Возвраты
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: string
        - name: count
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrgsBills'
      tags:
        - panel
  /panel/missed-calls:
    get:
      operationId: PanelController_getMissedCalls
      summary: Пропущенные звонки
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: string
        - name: count
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrgsBills'
      tags:
        - panel
  /panel/refusal:
    post:
      operationId: PanelController_refusalApplication
      summary: Передать заявку в отказ
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqRefusalDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrgsBills'
      tags:
        - panel
  /products:
    get:
      operationId: ProductsController_getProducts
      summary: Получение товаров по запросу
      parameters:
        - name: q
          required: false
          in: query
          schema:
            type: string
        - name: page
          required: true
          in: query
          schema:
            type: string
        - name: count
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
      tags:
        - products
  /products/one-product/{id}:
    get:
      operationId: ProductsController_getProduct
      summary: Получение товара
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
      tags:
        - products
  /products/similar-products:
    get:
      operationId: ProductsController_getSimilarProducts
      summary: Получение товаров по запросу
      parameters:
        - name: q
          required: false
          in: query
          schema:
            type: string
        - name: page
          required: true
          in: query
          schema:
            type: string
        - name: count
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
      tags:
        - products
  /applications/{id}:
    get:
      operationId: ApplicationsController_getApplication
      summary: Получение заявки
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponseDto'
      tags:
        - applications
  /sales/{id}:
    get:
      operationId: SalesController_getSale
      summary: Получение продажи
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleResponseDto'
      tags:
        - sales
info:
  title: WT PANEL
  description: ''
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    SignInRequestDto:
      type: object
      properties:
        phone:
          type: string
          example: '+79129656125'
        password:
          type: string
          example: Сергеев121
      required:
        - phone
        - password
    Role:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
      required:
        - id
        - title
    SessionInfoDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        company:
          type: string
        post:
          type: string
        birth_date:
          type: string
        personal_phone:
          type: string
        work_phone:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
      required:
        - id
        - name
        - company
        - post
        - birth_date
        - personal_phone
        - work_phone
        - roles
    BadApplication:
      type: object
      properties:
        count:
          type: string
        state:
          type: string
      required:
        - count
        - state
    Category:
      type: object
      properties:
        count:
          type: number
        title:
          type: string
        type:
          type: string
      required:
        - count
        - title
        - type
    InfoDto:
      type: object
      properties:
        pages:
          type: number
        count:
          type: number
      required:
        - pages
        - count
    ResponsibleDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
      required:
        - id
        - name
        - phone
    PorterDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
      required:
        - id
        - name
        - phone
    DataDto:
      type: object
      properties:
        id:
          type: string
        client:
          type: string
        responsible:
          $ref: '#/components/schemas/ResponsibleDto'
        processing:
          type: string
        sub_processing:
          type: string
        porter:
          $ref: '#/components/schemas/PorterDto'
        flag:
          type: number
      required:
        - id
        - client
        - responsible
        - processing
        - sub_processing
        - porter
        - flag
    ApplicationSaleDto:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/InfoDto'
        data:
          type: array
          items:
            $ref: '#/components/schemas/DataDto'
      required:
        - info
        - data
    MoveApplicationSaleDto:
      type: object
      properties:
        id:
          type: string
        processing:
          type: string
        sub_processing:
          type: string
        type:
          type: string
        move_myself:
          type: boolean
      required:
        - id
        - processing
        - sub_processing
        - type
        - move_myself
    CreateSaleDto:
      type: object
      properties:
        id:
          type: string
        org:
          type: string
        bill:
          type: string
      required:
        - id
        - org
        - bill
    Org:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    OrgsInfo:
      type: object
      properties:
        count:
          type: number
        data:
          type: array
          items:
            $ref: '#/components/schemas/Org'
      required:
        - count
        - data
    Bill:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    BillsInfo:
      type: object
      properties:
        count:
          type: number
        data:
          type: array
          items:
            $ref: '#/components/schemas/Bill'
      required:
        - count
        - data
    OrgsBills:
      type: object
      properties:
        orgs:
          $ref: '#/components/schemas/OrgsInfo'
        bills:
          $ref: '#/components/schemas/BillsInfo'
      required:
        - orgs
        - bills
    ReqRefusalDto:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    ProductInfo:
      type: object
      properties:
        pages:
          type: number
        count:
          type: number
      required:
        - pages
        - count
    ProductDto:
      type: object
      properties:
        indcode:
          type: string
        name:
          type: string
        cost:
          type: string
        comment:
          type: string
        article:
          type: string
        photos:
          type: array
          items:
            type: string
        sklad:
          type: string
      required:
        - indcode
        - name
        - cost
        - comment
        - article
        - photos
        - sklad
    ProductsResponse:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/ProductInfo'
        data:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
      required:
        - info
        - data
    Application:
      type: object
      properties:
        id:
          type: string
        date:
          type: number
      required:
        - id
        - date
    ApplicationInfo:
      type: object
      properties:
        id:
          type: string
        date:
          type: number
        client:
          type: number
        application:
          $ref: '#/components/schemas/Application'
        processing:
          type: string
        status:
          type: string
        store_keeper:
          type: string
        responsible:
          type: string
        sum:
          type: string
      required:
        - id
        - date
        - client
        - application
        - processing
        - status
        - store_keeper
        - responsible
        - sum
    ApplicationDto:
      type: object
      properties:
        name:
          type: string
        position:
          type: string
        cost:
          type: string
        count:
          type: string
        sum:
          type: string
        issued:
          type: string
        code:
          type: string
        id:
          type: string
        place:
          type: string
        photos:
          type: array
          items:
            type: string
        state:
          type: string
        article:
          type: string
        availability_in_k_warehouse:
          type: number
      required:
        - name
        - position
        - cost
        - count
        - sum
        - issued
        - code
        - id
        - place
        - photos
        - state
        - article
        - availability_in_k_warehouse
    ApplicationResponseDto:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/ApplicationInfo'
        data:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationDto'
      required:
        - info
        - data
    SaleInfo:
      type: object
      properties:
        id:
          type: string
        date:
          type: number
        client:
          type: number
        application:
          $ref: '#/components/schemas/Application'
        processing:
          type: string
        status:
          type: string
        store_keeper:
          type: string
        responsible:
          type: string
        sum:
          type: string
      required:
        - id
        - date
        - client
        - application
        - processing
        - status
        - store_keeper
        - responsible
        - sum
    SaleDto:
      type: object
      properties:
        name:
          type: string
        position:
          type: string
        cost:
          type: string
        count:
          type: string
        sum:
          type: string
        issued:
          type: string
        code:
          type: string
        id:
          type: string
        place:
          type: string
        photos:
          type: array
          items:
            type: string
        state:
          type: string
        article:
          type: string
        availability_in_k_warehouse:
          type: number
      required:
        - name
        - position
        - cost
        - count
        - sum
        - issued
        - code
        - id
        - place
        - photos
        - state
        - article
        - availability_in_k_warehouse
    SaleResponseDto:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/SaleInfo'
        data:
          type: array
          items:
            $ref: '#/components/schemas/SaleDto'
      required:
        - info
        - data
